//H 
// contiene tutti gli headers che derivano dalla cartella di lammps che ho utilizzato per il run del mio caso. Se si vuole simulare altro con funzioni specifiche trovate in lammps, gli header devono essere copiati dalla cartella src di lammps qui.


#include "lammps.h"         // these are LAMMPS include files
#include "input.h"
#include "atom.h"
#include "library.h"
#include "atom.h"
#include "molecule.h"
#include "fix.h"
#include "fix_external.h"
#include "modify.h"  
#include "OFstream.H"
#include "IOstream.H"    
#include "ISstream.H"   
#include "read_data.h"
#include <cstdlib>


